In [ ]:
'''import pandas as pd
df = pd.read_csv("Data/survey_results_public.csv")
df
df.shape
df.info()
pd.set_option("display.max_columns", 85)
df
schema_df = pd.read_csv('Data/survey_results_schema.csv')
pd.set_option("display.max_rows", 85)
schema_df
schema_df.head()'''

In [ ]:
#working with dictionaries

'''person = {                                       #we can use a dictionary as a table
    "first": "Corey", 
    "last": "Schafer",
    "email": "CoreyMSchafer@gmail.com"
}


people = {                                       #we can use a list inside a dictionary to add more no. of people
    "first": ["Corey"],
    "last": ["Schafer"],
    "email": ["CoreyMSchafer@gmail.com"]
}'''


people = {
    "first": ["Corey", 'Jane', 'John' ],
    "last": ["Schafer", 'Doe', 'Doe'],
    "email": ["Corey MSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

people["email"]

import pandas as pd
df = pd.DataFrame(people)
df
df['email']
type(df['email'])
df[['last','email']]
df.iloc[0]
df.iloc[[0,1]]
df.iloc[[0,1],[2,1]]

In [23]:
df = pd.read_csv("Data/survey_results_public.csv")
schema_df = pd.read_csv('Data/survey_results_schema.csv')
df['Hobbyist']
df['Country'].value_counts()
df.loc[17,'Hobbyist']
df.columns
df.loc[0:2,'Hobbyist':'Employment']
df

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [22]:
people = {
    "first": ["Corey", 'Jane', 'John' ],
    "last": ["Schafer", 'Doe', 'Doe'],
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}
df = pd.DataFrame(people)
df.set_index('email')
df.set_index('email', inplace = True)
df

                         first     last
email
CoreyMSchafer@gmail.com  Corey  Schafer
JaneDoe@email.com         Jane      Doe
JohnDoe@email.com         John      Doe

In [25]:
import pandas as pd
df = pd.read_csv('data/survey_results_public.csv', index_col='Respondent')
schema_df = pd.read_csv('Data/survey_results_schema.csv', index_col ='Column')
df
schema_df
schema_df.loc["SurveyEase", "QuestionText"]

'How easy or difficult was this survey to complete?'

In [ ]:
people = {
    "first": ["Corey", 'Jane', 'John' ],
    "last": ["Schafer", 'Doe', 'Doe'],
    "email": ["Corey MSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}
df = pd.DataFrame(people)
filt = (df['last']=="Schafer")
df[filt]

#or

df[df['last']=="Doe"]

# we can also use the loc function to get the same output but we can also filterout the required columns as shown below
df.loc[filt,'email']

filt = (df['last']=="Schafer") & (df['first']=='Corey')
df.loc[filt]

filt = (df['last']=="Schafer") | (df['first']=='John')
df.loc[filt]


filt = (df['last']=="Schafer") | (df['first']=='John')
df.loc[~filt]

In [ ]:
df = pd.read_csv('data/survey_results_public.csv', index_col='Respondent')
schema_df = pd.read_csv('Data/survey_results_schema.csv', index_col ='Column')
pd.set_option("display.max_columns", 85)
pd.set_option("display.max_rows", 85)
df.head()
schema_df.loc["ConvertedComp", "QuestionText"]
HighSal = (df['ConvertedComp']>70000)
Filt = ['Country','ConvertedComp','MgrIdiot']
df.loc[HighSal,Filt]

countries = ['India','Canada','United States', 'Germany', 'United Kingdom']
Filt = df['Country'].isin(['India','Canada','United States', 'Germany', 'United Kingdom'])
df.loc[Filt,'Country']

Filt1 = df['Country'].isin(['India','Canada','United States', 'Germany', 'United Kingdom'])&(df['ConvertedComp']>70000)
df.loc[Filt]

filt = (df['LanguageWorkedWith'].str.contains("Python", na=False))
df[filt]

#we can also use this to search schema_df
'''filt = (schema_df['QuestionText'].str.contains("Salary", na=False))
df.loc(filt)'''

In [ ]:
People = {
    "first": ['Corey', 'Jane', 'John', 'Peter' ],
    "last": ['Schafer', 'Doe', 'Doe', 'Parker'],
    "email": ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com', 'PeterSpideyParker@gmail.com']
}

df = pd.DataFrame(People)
df

#if i want to change the column names
df.columns
df.columns = ['First Name', 'Last Name', 'email']
df


# to change the case of all column headings
df.columns = [x.upper() for x in df.columns]
df

#to replace a partular value in all the columns
df.columns = (df.columns.str.replace(' ','_'))
df

#if we want to change a particular column
df.rename(columns={"FIRST_NAME":"first", "LAST_NAME":"last", "EMAIL":"email"}, inplace = True)
df

#if we wanted to change john doe to john smith

#df.loc[2] = ['John','Smith','JohnSmith@email.com']
filt = (df['first']=='John')&(df['last']=='Doe')
df.loc[filt] = ['John','Parker','JohnParker@email.com']
#or we could use the column feature of loc and update just the required columns
df.loc[filt,['last','email']] = ['Smith','JohnSmith@email.com']
df

#to change a particular column to lowercase
df['first']= df['first'].str.lower()
df

#APPLY
df['email'].apply(len)            #gives us length of each cell in email column
df.apply(len)                     #gives us number of rows present basically len(df['email']) for every column
len(df['email'])
df.apply(len, axis = 'columns')   #gives us number of columns present




People = {
    "first": ['Corey', 'Jane', 'John', 'Peter' ],
    "last": ['Schafer', 'Doe', 'Doe', 'Parker'],
    "email": ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com', 'PeterSpideyParker@gmail.com'],
    "salary":[10000,20000,30000,25000]
}

df = pd.DataFrame(People)

def UpdateEmail(Email):
    if type(Email)== 'str':
        return Email.upper()
    else:
        return Email
    
df.apply(UpdateEmail)



'''def UpdateEmail(Email):
        return Email.upper()
df.apply(UpdateEmail)''' #this code gives an errror because we cannot apply string functions to numbers

    
df.apply(pd.Series.min) #gives us the minimum value in each column (usually used for numbers but in case of string the smallest letter is chosen)







#APPLYMAP



people = {
    "first": ["Corey", 'Jane', 'John' ],
    "last": ["Schafer", 'Doe', 'Doe'],
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

DF = pd.DataFrame(people)

DF.applymap(len)
DF.applymap(str.lower)




People = {
    "first": ['Corey', 'Jane', 'John', 'Peter' ],
    "last": ['Schafer', 'Doe', 'Doe', 'Parker'],
    "email": ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com', 'PeterSpideyParker@gmail.com'],
    "salary":[10000,20000,30000,25000]
}

df = pd.DataFrame(People)

def Len(para):
    if type(para)== str:
        return len(para)
    else:
        return 'Na'
    
df.applymap(Len)


df

df['first'].map({'Corey':'Chris','Jane':'Mary'})      #the issue with this method is that it by default prints NaN for all not required cells

#to over come this we can use replace

df['first']=df['first'].replace({'Corey':'Chris','Jane':'Mary'})
df

In [ ]:
import pandas as pd
df = pd.read_csv('data/survey_results_public.csv', index_col='Respondent')
schema_df = pd.read_csv('Data/survey_results_schema.csv', index_col ='Column')
pd.set_option("display.max_columns", 85)
pd.set_option("display.max_rows", 85)


#change 'ConvertedComp' to Salary
df.rename(columns={'ConvertedComp':'SalaryUSD'},inplace=True)
df

#change yes or no in Hobbyist to True or False
df['Hobbyist']=df['Hobbyist'].replace({'Yes':'True', 'No':'False'})
df

In [ ]:
People = {
    "first": ['Corey', 'Jane', 'John', 'Peter' ],
    "last": ['Schafer', 'Doe', 'Doe', 'Parker'],
    "email": ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com', 'PeterSpideyParker@gmail.com']
}

df = pd.DataFrame(People)
# to create a new column with eixsting but modified values
df['first']+' '+df['last']
df['full']=df['first']+' '+df['last']
df

#to delete a column
df.drop(columns=['first','last'],inplace = True) #add inplace = True for the values to get updated in the real table

#to split a column and add 2 new columns
df[['first','last']]=df['full'].str.split(' ', expand=True)
df

#to add a row of values

df._append({'first':'Tony'}, ignore_index = True)

#to add other dataframe to an existing dataframe

people2 = {
    "first": ['Tony', 'Steve' ],
    "last": ['Stark', 'Rogers'],
    "email": ['TonyStark@avengers.com', 'SteveRogers@avengers.com']
}
df2 = pd.DataFrame(people2)
#df=df._append(df2,ignore_index = True, sort = True)  #will sort columns in ascending order
df=df._append(df2,ignore_index = True) 
df


#we can also delete columns usng index
df.drop(index=4,inplace = True)
filt = (df['first']=='Steve')&(df['last']=='Rogers')
df.drop(index = df[filt].index, inplace = True)
df

In [ ]:
import pandas as pd
People = {
    "first": ['Corey', 'Jane', 'John', 'Adam' ],
    "last": ['Schafer', 'Doe', 'Doe', 'Doe'],
    "email": ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com', 'AdamDoe@gmail.com']
}

df = pd.DataFrame(People)


df.sort_values(by='last',inplace = True)
df.sort_values(by='last',ascending = False, inplace = True)
df.sort_values(by=['last','first'],ascending = [False,True], inplace = True)
df

#to get back orignal table
df.sort_index(inplace = True)
df

In [ ]:
import pandas as pd
df = pd.read_csv('data/survey_results_public.csv', index_col='Respondent')
schema_df = pd.read_csv('Data/survey_results_schema.csv', index_col ='Column')
pd.set_option("display.max_columns", 85)
pd.set_option("display.max_rows", 85)
df.sort_values(by=['Country','ConvertedComp'], ascending = [True,False],inplace = True)
df[['Country','ConvertedComp']].head(50)
df['ConvertedComp'].nlargest (10)
df.nlargest (10, 'ConvertedComp')

In [44]:
import pandas as pd
df = pd.read_csv('data/survey_results_public.csv', index_col='Respondent')
schema_df = pd.read_csv('Data/survey_results_schema.csv', index_col ='Column')
pd.set_option("display.max_columns", 85)
pd.set_option("display.max_rows", 85)
df['ConvertedComp'].median()
df.median(numeric_only=True)

df.describe()

df['ConvertedComp'].count()

df['SocialMedia'].value_counts()
df['SocialMedia'].value_counts(normalize=True)



#using groupby functions

country_group = df.groupby(['Country'])
#country_group.get_group('United States')
country_group['SocialMedia'].value_counts().head(50)
#country_group['SocialMedia'].value_counts().loc['Russian Federation']



#to see the median salary of each country
country_group['ConvertedComp'].median()
country_group['ConvertedComp'].median().loc['India']
country_group['ConvertedComp'].agg(['median','mean']).loc['India']

# to see how many people in india know python

#country_group['LanguageWorkedWith'].str.contains('Python').loc['India']         #this will give us an error

country_group = df.groupby(['Country'])
#country_group['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

def func(x):
    return x.str.contains('Python').sum()
country_group['LanguageWorkedWith'].apply(func)

#what % of people work with python ?

cr = df['Country'].value_counts()
cr

cup = country_group['LanguageWorkedWith'].apply(func)

pdf = pd.concat([cr,cup], axis='columns')
pdf
pdf.columns = ['NoOfCoders','PythonCoders']
pdf

pdf['PctPythonCoders'] = 100*(pdf['PythonCoders']/pdf['NoOfCoders'])
pdf
pdf.sort_values(by='PctPythonCoders', ascending = False, inplace = True)
pdf.head(50)
pdf.loc['Japan']

NoOfCoders         391.000000
PythonCoders       182.000000
PctPythonCoders     46.547315
Name: Japan, dtype: float64

In [8]:
import pandas as pd
import numpy as np

people = {
    'first': ['Corey', 'Jane', 'John', 'Chris', np.nan, None, 'NA'], 
    'last': ['Schafer', 'Doe', 'Doe', 'Schafer', np.nan, np.nan, 'Missing'], 
    'email': ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com', None, np.nan, 'Anonymous@email.com', 'NA'],
    'age': ['33', '55', '63', '36', None, None, 'Missing']
}
df = pd.DataFrame(people)
df.dropna()
df.dropna (axis='index', how='any')
df.dropna (axis='index', how='all')
df.dropna (axis='columns', how='all')
df.dropna (axis='columns', how='all')
df.dropna (axis='index', how='any', subset = ['email'])
df.dropna (axis='index', how='all', subset = ['email'])

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
5   None      NaN      Anonymous@email.com     None
6     NA  Missing                       NA  Missing